[project]
name = "fastapi-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sukanya V S", email = "sukanyas@xminds.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.20.0",
    "fastapi>=0.141.1",
    "psycopg2-binary>=2.9.13",
    "sqlalchemy>=2.1.1",
    "uvicorn[standard]>=0.54.0",
]

[project.scripts]
fastapi-project = "fastapi_project:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
